framework:
    messenger:
        transports:
            check_video: '%env(MESSENGER_TRANSPORT_DSN)%check_video'
            scan_file: '%env(MESSENGER_TRANSPORT_DSN)%scan_file'
            scan_directory: '%env(MESSENGER_TRANSPORT_DSN)%scan_directory'
        routing:
            'Pbxg33k\MessagePack\Message\ScanFileMessage': scan_file
            'Pbxg33k\MessagePack\Message\ScanDirectoryMessage': scan_directory
            'Pbxg33k\MessagePack\Message\CheckVideoMessage': check_video
